#!/usr/bin/env node

const Twetch = require('./dist/twetch.node.min.js');
const twetch = new Client();

console.log('Twetch SDK CLI');

(async () => {
	await twetch.publish('twetch/post@0.0.1', {
		bContent: process.argv[2],
		bFilename: `twetch-${new Date().getTime()}.txt`,
		mapTimestamp: `${(process.hrtime()[0] * 1000000000 + process.hrtime()[1]).toString()}`
	});
	process.exit();
})();
