#!/usr/bin/env node

const Twetch = require('./dist/twetch.node.min.js');
const twetch = new Twetch();

console.log('Twetch SDK CLI');

(async () => {
	await twetch.publish('twetch/post@0.0.1', {
		bContent: process.argv[2]
	});
	process.exit();
})();
